spring.application.name=api-gateway
# App Name

#  Server Port
server.port=8080

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable Load Balancer (important for lb://)
spring.cloud.loadbalancer.enabled=true


# ===============================
# ROUTES CONFIGURATION
# ===============================

spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://productservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**


spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory/**